# Generated by Django 5.2.3 on 2025-06-28 19:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='fas fa-cube', help_text='FontAwesome icon class', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model_number', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('suitable_for', models.TextField(help_text='Description of who this equipment is suitable for')),
                ('dimensions', models.CharField(help_text='e.g., 3.5m x 2.8m x 2.1m', max_length=100)),
                ('safety_zone', models.CharField(help_text='Required safety zone around equipment', max_length=100)),
                ('max_users', models.PositiveIntegerField(default=1, help_text='Maximum simultaneous users')),
                ('age_group', models.CharField(choices=[('toddler', 'Toddler (1-3 years)'), ('preschool', 'Preschool (3-5 years)'), ('school_age', 'School Age (5-12 years)'), ('teen', 'Teen (12-16 years)'), ('adult', 'Adult (16+ years)'), ('all_ages', 'All Ages')], max_length=20)),
                ('material', models.CharField(choices=[('steel', 'Steel'), ('aluminum', 'Aluminum'), ('wood', 'Wood'), ('plastic', 'Plastic'), ('composite', 'Composite'), ('galvanized_steel', 'Galvanized Steel'), ('stainless_steel', 'Stainless Steel')], max_length=20)),
                ('safety_standard', models.CharField(choices=[('en1176', 'EN 1176 (European)'), ('astm_f1487', 'ASTM F1487 (US)'), ('as4685', 'AS 4685 (Australian)'), ('csa_z614', 'CSA Z614 (Canadian)'), ('custom', 'Custom Standard')], max_length=20)),
                ('maintenance_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('foundation_required', models.BooleanField(default=True)),
                ('installation_time', models.CharField(help_text='e.g., 2-3 days', max_length=50)),
                ('warranty_years', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='equipment/')),
                ('gallery_images', models.JSONField(blank=True, default=list, help_text='List of additional image URLs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category')),
            ],
            options={
                'verbose_name_plural': 'Equipment',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('inquiry_type', models.CharField(choices=[('quote', 'Request Quote'), ('info', 'Request Information'), ('consultation', 'Request Consultation'), ('installation', 'Installation Inquiry'), ('maintenance', 'Maintenance Inquiry'), ('other', 'Other')], max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_responded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.equipment')),
            ],
            options={
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('project_type', models.CharField(choices=[('playground', 'Playground'), ('street_workout', 'Street Workout'), ('fitness_park', 'Fitness Park'), ('school', 'School'), ('park', 'Public Park'), ('residential', 'Residential'), ('commercial', 'Commercial')], max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('client', models.CharField(blank=True, max_length=200)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('project_duration', models.CharField(blank=True, help_text='e.g., 3 weeks', max_length=50)),
                ('budget_range', models.CharField(blank=True, help_text='e.g., €50,000 - €75,000', max_length=50)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('gallery_images', models.JSONField(blank=True, default=list)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment_used', models.ManyToManyField(blank=True, to='catalog.equipment')),
            ],
            options={
                'ordering': ['-is_featured', '-completion_date'],
            },
        ),
    ]
