# Generated by Django 5.2.3 on 2025-06-30 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_material_themeline_remove_equipment_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='material',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='themeline',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='themeline',
            name='slug',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='main_image',
            field=models.CharField(blank=True, help_text='URL to the main image in Supabase Storage', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='materials',
            field=models.ManyToManyField(blank=True, db_table='catalog_equipment_material', to='catalog.material'),
        ),
        migrations.AlterModelTable(
            name='material',
            table='catalog_material',
        ),
        migrations.AlterModelTable(
            name='themeline',
            table='catalog_theme_line',
        ),
    ]
