# Generated by Django 5.2.3 on 2025-07-07 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_material_is_active_remove_material_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'catalog_equipment_type',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='has_variant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipment',
            name='material',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='age_group',
            field=models.CharField(choices=[('0-3 godine', '0-3 godine'), ('3-12 godina', '3-12 godina'), ('12-16 godina', '12-16 godina'), ('16+ godina', '16+ godina')], max_length=20),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='model_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='equipment',
            unique_together={('model_number', 'theme_line')},
        ),
        migrations.AddField(
            model_name='equipment',
            name='types',
            field=models.ManyToManyField(blank=True, db_table='catalog_equipment_type_link', to='catalog.equipmenttype'),
        ),
        migrations.CreateModel(
            name='EquipmentVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=100, null=True)),
                ('safety_zone', models.CharField(blank=True, max_length=100, null=True)),
                ('max_users', models.IntegerField(blank=True, null=True)),
                ('equipment', models.ForeignKey(db_column='equipment_id', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.equipment')),
                ('material', models.ForeignKey(blank=True, db_column='material_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.material')),
                ('theme_line', models.ForeignKey(blank=True, db_column='theme_line_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.themeline')),
            ],
            options={
                'db_table': 'catalog_equipment_variant',
            },
        ),
    ]
