# Generated by Django 5.2.3 on 2025-07-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_equipmenttype_equipment_has_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentvariant',
            name='materials',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
