# Generated by Django 5.2.3 on 2025-07-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_equipmentvariant_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='dwg_files',
            field=models.JSONField(blank=True, default=list, help_text='Lista DWG datoteka (linkova)'),
        ),
    ]
