# Generated by Django 5.2.3 on 2025-07-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_equipment_dwg_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='main_image',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list, help_text='Lista slika (prva slika se koristi kao glavna slika)'),
        ),
    ]
